package exception1;

public class throw2 {

	public static void main(String[] args) {
		if(-3<0)
			throw new ArithmeticException("error");
		System.out.println("hii");
		

	}

}
